### ISSUE TITLE
EPIC: MVP2 - verwerkingenlogging register

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/verwerkingenlogging#11]
# Research

## Fase 1
- [x] #52 
- [x] #56
- [x] #59
- [x] #57
- [x] #54
- [x] #58
- [x] #64

## Fase 2
- [x] #62
- [x] #61
- [x] #60
- [x] #84

# Technical

## Fase 1
- [x] #63
- [x] #82
- [x] #83
- [x] #87
- [x] #88
- [x] #89

# Description

**Correct verwerken van alle api-calls.**
    - Dit gaat over zowel het verwerken van de juiste verzoeken vanuit de applicatie als het geven van de juiste response.
        - POST/verwerkingsacties: geeft momenteel te veel informatie terug (objectTypeSoortId is niet nodig om terug te geven)
        - GET/verwerkingsacties: geeft moment een lijst met veldnaam “Items” terwijl de standaard “Results” adviseert.
        - PATCH/verwerkingsacties: geeft momenteel een resultaat van de wijzigingsactie als test. Geen response is verplicht.
        - GET/verwerkingsacties/{actieId}: geeft ook nog ‘objectTypeSoortId’ veld terug
        - PUT/verwerkingsacties/{actieId}: geeft ook nog ‘objectTypeSoortId’ veld terug
        - DELETE/verwerkingsacties/{actieId}: geeft een test response. Geen response is verplicht.

**Validatie op de verplichte velden**
    - Zodra een verplicht veld niet aanwezig is moet de verwerkingenlog dit met een passende response aan de applicatie laten weten.
    - Zie SIM voor de verplichten velden. https://vng-realisatie.github.io/gemma-verwerkingenlogging/gegevensmodel/semantisch_informatiemodel 

**Pseudonimisering van de BSN (zie B2042)**
    - De VNG heeft besloten de pseudonimisering volledig achter de API te laten plaatsvinden.
    - De implementatie van de API versleutelt het BSN en neemt dit op in het verwerkingenlog.

**Comment by marnixdessing** [comment]
Kan eind sprint 12 gesloten worden als het goed is
