### ISSUE TITLE
PROJECT: Verwerkingenlogging

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/verwerkingenlogging#137]
Loggen van verwerkingen en het tonen hiervan op Mijn Nijmegen. 
Intake: https://irvn.sharepoint.com/sites/NijmegenAfstemmingsoverleg/Lists/Intakes/DispForm.aspx?ID=762&Source=https%3A%2F%2Firvn%2Esharepoint%2Ecom%2Fsites%2FNijmegenAfstemmingsoverleg%2FLists%2FIntakes%2FDoing%2Easpx%23InplviewHashddf867fe%2Dba8b%2D4973%2D91d0%2D121ef78669f3%3D&ContentTypeId=0x01008DB40EF2E2C16F47964C85F514CE4F3A

Volgorde applicaties:

- [ ] 1. inzendingen webformulieren
- [ ] 2. tussentijds opslaan webformulieren
- [ ] 3. verwerkingen als gevolg van inloggen en vervolgens het 'afbreken van de aanvraag' (niet inzenden of tussentijds opslaan van het webformulier)
- [ ] 4. BRP ophalen om in yivi op te nemen
- [ ] 5. tribe
- [ ] 6. Vip
- [ ] 7. VrijBRP

@BramWithaar wil jij dit project aanvullen?

**Comment by MartijnvDijk** [comment]
De stand van zaken is dat de doorontwikkeling en verdere vaststelling van de verwerkingenlog standaard door het MT van VNG-R is stilgelegd. Dit in verband met (a) het aan VNG gegeven juridisch advies, en (b) de ontwikkeling van de Logboek Dataverwerkingen standaard van BZK. Deze laatste lijkt kansrijk te zijn voor opname in de GDI en daarmee zal het de nationale standaard te worden die ook VNG zal gaan volgen.
 
Dit is denk ik niet het bericht waar je op hoopte. Ik ben er zelf ook niet gelukkig mee aangezien ik denk dat de VNG standaard een aantal voordelen heeft boven de standaard van BZK.
