### ISSUE TITLE
Readme actualiseren en corrigeren

### ISSUE THREAD

**Issue by adgerrits** [GemeenteNijmegen/verwerkingenlogging#250]
Supermooi dat Nijmegen deze comcept-standaard al toepast en de implementatie als voorbeeld kan dienen voor anderen (en misschien t.z.t. als 'best practice' op te nemen op GEMMA Online....). Maar 'adel verplicht' dus een goeie Readme, het eerste waar mensen naar kijken, is wel nodig. Er zitten nu wat fouten in zoals:
- taalfouten: "moeten alle verwerkingen van de aangesloten system", "informatiesystem", "Toegangkelijkheid" (mogelijk al in de VNG-tekst dus nog mooier die aan te passen...)
- outdated info: "6. DB structuur (OUTDATED)"
- dode link: "De API voor inzage van verwerkingen door betrokkenen en derden is [hier] te vinden."

Dus kwestie van de poetsdoek er even bij pakken en zorgen dat zo'n mooie inhoud een net zo mooie kadoverpakking heeft.

**Comment by BramWithaar** [comment]
paragraaf 6 verwijderd voor nu, mag @MartijnvDijk een goede nieuwe versie voor maken. Andere typo's en dode link opgelost.

**Comment by MartijnvDijk** [comment]
Verder actualiseren zal volgende sprint opgepakt worden
