### ISSUE TITLE
Readme versimpelen

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/verwerkingenlogging#310]
Informatiedocument verplaatsen naar docs. Readme veranderen in simpele uitleg over verwerkingenlogging

**Comment by BramWithaar** [comment]
Onze bijzonderheden / implementatie / hoe te hergebruiken bovenaan in het document zetten?
Voor alle generieke verwerkingslog dingen gewoon verwijzen naar de verwerkingslog GitHub? (geen dingen dubbel schrijven).
Simpele howto met instructies om te deployen (met vereisten aan een AWS account)
