### ISSUE TITLE
publiceren op opencatalogi

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/verwerkingenlogging#331]
We willen de verwerkingenlog oplossing publiceren op https://opencatalogi.nl zodat die beter vindbaar is voor andere potentiële geïnteresseerden.

daarvoor moet een publiccode.yaml opgenomen worden in de repo, en de repo moet aangemeld worden bij opencatalogi
https://github.com/marketplace/actions/create-or-update-publiccode-yaml

```[tasklist]
### Tasks
- [x] Uitzoeken waarom publiceren nog niks oplevert: https://samenorganiseren.slack.com/archives/C049GJ0QNHW/p1708000432621789
- [ ] https://github.com/GemeenteNijmegen/verwerkingenlogging/issues/335
```

**Comment by BramWithaar** [comment]
Publiceren naar opencatalogi is gelukt, het spul indexeert wel meteen alle publieke repo's:
https://opencatalogi.nl/organizations/3665c870-8998-4591-a34d-021ac3066922/

**Comment by MartijnvDijk** [comment]
Nieuw issue: https://github.com/GemeenteNijmegen/verwerkingenlogging/issues/335 

Deze sluiten
