### ISSUE TITLE
verwerkingenlog publiccode.yaml voorzien van correcte metadata

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/verwerkingenlogging#335]

**Comment by BramWithaar** [comment]
hier staat wat er ingevuld kan worden: https://github.com/OpenCatalogi/.github/blob/main/docs/handleidingen/Publiccode.md#welke-velden-kan-ik-verwachten-in-een-publiccode

de .yaml kan handmatig aangepast worden met de gewenste waarden. Uitzoeken dus wat er in moet en dat dan doen
