### ISSUE TITLE
Onderzoek: eventbridge ipv lambda / sqs

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/verwerkingenlogging#67]
https://dev.to/aws-builders/three-serverless-lambda-less-api-patterns-with-aws-cdk-4eg1

http://biggscloud.com/2020/10/01/api-gateway-to-eventbridge-integration/
The biggest concern is what happens when the webhook receives a large amount of (burst) traffic, and the lambda reaches a maximum amount (default=1000) of invocations? HINT: it involves either provisioning a massive amount of resources, or not being able to respond to all the requests ie. expensive or not good.

**Comment by joostvanderborg** [comment]
Als ik de goeie heb is dit ook een interessante in dit verband: https://www.youtube.com/watch?v=o6-7BAUWaqg

**Comment by MartijnvDijk** [comment]
Step functions is ook nog iets om mee te nemen

**Comment by MartijnvDijk** [comment]
Step functions kan op twee manieren draaien (workflows), standaard en express. Standaard is 0.42$ per duizend executions en express maar 0.01$ per duizend. Probleem bij de express workflow is dat het 'at least once' is. Er bestaat dus geen zekerheid dat een bericht via deze workflow niet dubbel wordt verstuurd.

**Comment by MartijnvDijk** [comment]
Conclusie: use-case te ingewikkeld om hier nu step functions voor te gaan  gebruiken. Eventbridge blijft een lastig verhaal omdat we graag een directe response willen geven waarin twee attributen gegenereerd moeten worden. Lambda blijft voor nu de logische keuze.
